# Generated by Django 6.0.1 on 2026-01-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_qrtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrtoken",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
