# Generated by Django 6.0.1 on 2026-01-17 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_qrtoken_is_used"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attendancesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("teacher",),
                name="one_active_session_per_teacher",
            ),
        ),
    ]
