# Generated by Django 6.0.1 on 2026-01-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_attendancerecord_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendancesession",
            name="one_active_session_per_teacher",
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="radius_meters",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
