# Generated by Django 5.0.6 on 2026-01-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0006_remove_attendancesession_one_active_session_per_teacher_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="end_time",
            field=models.DateTimeField(),
        ),
    ]
