# Generated by Django 5.0.6 on 2026-01-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_attendancesession_duration_minutes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesession",
            name="radius_meters",
            field=models.PositiveIntegerField(default=150),
        ),
    ]
