# Generated by Django 5.0.6 on 2026-01-27 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("ATTENDANCE", "Attendance Sheet"),
                            ("EXAM", "Exam / Marks"),
                            ("TIMETABLE", "Timetable"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("HOLIDAY", "Holiday"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="teachers.teacherprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoticeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="notices/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="notices.notice",
                    ),
                ),
            ],
        ),
    ]
