# Generated by Django 6.0.1 on 2026-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_face_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_first_login",
            field=models.BooleanField(default=True),
        ),
    ]
